apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: partner-partner-endorser-auth-job
  annotations:
    flux.weave.works/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-partner-endorser-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: ssh://git@github.com/juraj-durech/blockchain-automation-framework.git
    ref: development-environment
  values:
    metadata:
      name: partner-partner-endorser-auth-job
      namespace: partner-ns
    network:
      name: baf
      kubernetes_url: https://10.25.3.21:6443
    image:
      name: partner
      repository: alpine:3.9.4
    vault:
      address: http://baf1.bafdev.uisp.accenture.com:15296
      keyPath: partner.endorsers
      identity: partner-endorser
      admin_auth_path: kubernetes-partner-admin-auth
      policy: partner-partner-endorser-ro
      policy_content: path \"/partner/endorsers/partner-endorser/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-partner-partner-endorser-auth
    account:
      admin_service: partner-admin-vault-auth
      admin_role: rw
      service: partner-partner-endorser-vault-auth
      role: ro
