apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: partner-dtg
  annotations:
    flux.weave.works/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: ssh://git@github.com/juraj-durech/blockchain-automation-framework.git
    ref: development-environment
  values:
    metadata:
      name: partner-dtg
      namespace: partner-ns
    organization:
      name: partner
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"SR36sg597jWuB4cbiVVnzZ","role":"0","verkey":"ErQC5pVFVkJpF3DjjA1r1BbAKPqkDerT7ch3SXaNVCT4"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-1","dest":"L6NJtcaDiDkyk7WCfRPsqr","role":"2","verkey":"BQZ4qY8owbNu8F2tMq8vMaqtE1t42VC3eBZYY4CdwVg6"},"metadata":{"from":"SR36sg597jWuB4cbiVVnzZ"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-2","dest":"2mF7VJCuXfCWNDV12hanut","role":"2","verkey":"xj7XXvZJSZRycCwUmcRUXsMxjysFMq8Uf2gT7oYpxKy"},"metadata":{"from":"SR36sg597jWuB4cbiVVnzZ"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-1","dest":"UBZVW7isG4Ge3ZAoSkVVhZ","role":"2","verkey":"FpHBCVZrjHv5a2NRTSA1JTCyqQ7F4fFQbNqQRqDfwyRe"},"metadata":{"from":"SR36sg597jWuB4cbiVVnzZ"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-2","dest":"Gg93x5UhKkZ4UKAVigRjwP","role":"2","verkey":"9YWfrpB41eFxnZzcSEmvw3gtLEwgNiQMV7YWCVXqE33g"},"metadata":{"from":"SR36sg597jWuB4cbiVVnzZ"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
