- hosts: ansible_provisioners
  gather_facts: no
  tasks:

# This role makes up the geth binary and place it in the bin directory
    - include_role:
        name: setup/geth
      loop: "{{ network['organizations'] }}"
      when: network.type == 'quorum'

# This role makes up the bootnode binary and place it in the bin directory
    - include_role:
        name: setup/bootnode
      loop: "{{ network['organizations'] }}"
      when: network.type == 'quorum'

# This role generates the crypto material for quorum network based on RAFT consensus and store it in vault
    - include_role:
        name: create/generate_crypto_raft
      vars:
        component_name: "{{ item.name | lower }}"
        component_ns: "{{ item.name | lower }}-net"
        vault: "{{ item.vault }}"
        peer: "{{ item.services.peers[0] }}"
      loop: "{{ network['organizations'] }}"
      when: network.type == 'quorum'

  vars: #These variables can be overriden from the command line
    bin_install_dir:  "~/bin"            #Default to /bin install directory for binaries
