#############################################################################################
# This role creates value files for namespaces of organizations
#############################################################################################

# Check if namespace created
- name: Check namespace is created
  k8s_facts:
    kind: Namespace
    name: "{{ component_name }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  register: get_namespace

############################################################################################
# This task creates the value file of Namespace for Organizations
- name: Create namespaces
  include_role:
    name: create/k8_component
  vars:    
    component_type: "namespace"    
  when: get_namespace.resources|length == 0

############################################################################################
#Git Push : Pushes the above generated files to git directory 
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_REPO: "{{ organizationItem.gitops.git_push_url }}"
    GIT_USERNAME: "{{ organizationItem.gitops.username }}"
    GIT_EMAIL: "{{ organizationItem.gitops.email }}"
    GIT_PASSWORD: "{{ organizationItem.gitops.password }}"
    GIT_BRANCH: "{{ organizationItem.gitops.branch }}"
    GIT_RESET_PATH: "platforms/hyperledger-indy/configuration"
    msg: "Pushing deployment files for namespace"
