#############################################################################################
# This role creates value file for the deployment of CA Tools CLI
#############################################################################################

# Check if CA server is available
- name: Check CA-server is available
  k8s_facts:
    kind: Pod
    namespace: "{{ component_name }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    label_selectors:
      - name = {{ component_services.ca.name }}
  register: get_ca
  until: ("Running" in get_ca|json_query('resources[*].status.phase'))
  retries: "{{ network.env.retry_count}}"
  delay: 30

############################################################################################
# This task creates the CA-tools value files
- name: "Create CA-tools Values"
  include_role:
    name: helm_component
  vars:
    name: "{{ ca.name }}-tools"
    type: "ca-tools"
    git_url: "{{ gitops.git_ssh }}"
    git_branch: "{{ gitops.branch }}"
    charts_dir: "{{ gitops.chart_source }}"

#Git Push : Pushes the above generated files to git directory 
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_REPO: "{{ item.gitops.git_push_url }}"
    GIT_USERNAME: "{{ item.gitops.username }}"
    GIT_EMAIL: "{{ item.gitops.email }}"
    GIT_PASSWORD: "{{ item.gitops.password }}"
    GIT_BRANCH: "{{ item.gitops.branch }}"
    GIT_RESET_PATH: "platforms/hyperledger-fabric/configuration"
    msg: "Pushing CA-tools files"

