# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Provide the number of replicas for pods
#Eg. replicaCount: 1
replicaCount: 

metadata:
  #Provide the namespace for the raft node
  #Eg. namespace: example-com
  namespace: 
  #Provide the custom labels  
  #NOTE: Provide labels other than name, release name , release service, chart version , chart name, run
  #These lables will not be applied to VolumeClaimTemplate of StatefulSet as labels are automatically picked up by Kubernetes
  #Eg. labels:
  #      role: minter
  labels: 

#These are the various docker images being used by this chart. update them as needed
images:
  #Provide the valid image name and version for quorum node
  #Eg. node: quorumengineering/quorum:2.1.1
  node: quorumengineering/quorum:2.1.1
  #Provide the valid image name and version to read certificates from vault server 
  #Eg. alpineutils: adopfrablockchain.azurecr.io/alpine-utils:1.0
  alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
  #Provide the valid image name and version for quorum constellation
  #Eg. constellation: quorumengineering/constellation:0.3.2
  constellation: quorumengineering/constellation:0.3.2

node:
  #Provide the name for raft node
  #Eg. name: node-1
  name: 
  #Provide the mountpath for Quorum pod
  #Eg. mountPath: /etc/quorum/qdata
  mountPath: 
  #Provide the docker secret name in the namespace
  #Eg. imagePullSecret: regcred
  imagePullSecret: regcred
  #Provide the keystore file name
  #Eg. keystore: keystore_1
  keystore: 
  #Provide the k8s service type
  servicetype: ClusterIP
  #Provide the container and service ports
  ports:
    rpc: 8546
    raft: 50401
    constellation: 9001
    quorum: 21000

vault:
  #Provide the Vault Address from where secrets will be read
  #Eg. address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9000
  address: 
  #Provide the Vault secret path from where secrets will be read
  #Eg. secretprefix: secret/org1/crypto/node_1
  secretprefix: 
  #Provide the serviceaccount which is verified with Vault
  #Eg. serviceaccountname: vault-auth
  serviceaccountname: 
  #Provide the key name from where secrets will be read
  #Eg. keyname: raft
  keyname: 
  #Provide the service role which is verified with Vault
  #Eg. role: vault-role
  role: 
  #Provide the Vault auth-path which is created for the namespace
  #Eg. authpath: quorumorg1
  authpath: 
    

#Provide the genesis file contents coded in base64 
#Eg. genesis: |
#      ewogICAgImFsbG9jIjogewogICAgICAgICIweDA5ODY3OTZmMzRkOGYxY2QyYjQ3YzczNDZhNTBi
#      ZjY5YWE5YzU3NzIiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjEwMDAwMDAwMDAwMDAwMDAw
#      MDAwMDAwMDAwMDAiCiAgICAgICAgfSwKICAgICAgICAiMHhmNjI5MjU0NWFlYzU5MjA1ODM0MTRl
genesis: 

#Provide the staticnodes file contents coded in base64 
#Eg. staticnodes: |
#      WwogICAgImVub2RlOi8vMjkzY2UwMjJiZjExNGIxNDUyMGFkOTczNDlhMTk5MDE4MDk3Mzg4NWNj
#      MmFmYjZmNDE5NmI0OTAzOTdlMTY0ZmFiYzg3OTAwNzM2ZTRiNjg1YzVmNGNmMzE0NzkwMjFiYTBk
#      NTg5ZTU4YmQwZWE2NzkyZWJiZmQ1ZWIwMzQ4YWZAbm9kZTEucXVvLmRlbW8uYXdzLmJsb2NrY2hh
staticnodes: 

constellation:
  #Provide the constellation url that is reachable other nodes 
  #Eg. url: 'http://node1.quo.demo.aws.blockchaincloudpoc.com:15013/'
  url:
  #Provide the constellation persistent data storage
  #Eg. storage: 'bdb:/etc/quorum/qdata/database'  # bdb:path (BerkeleyDB)
  storage: 
  #Provide if constellation will use tls. 
  # Options:
  ##   - strict: All connections to and from this node must use TLS with mutual
  ##     authentication. See the documentation for tlsservertrust and
  ##     tlsclienttrust below.
  ##   - off: Mutually authenticated TLS is not used for in- and outbound
  ##     connections, although unauthenticated connections to HTTPS hosts are
  ##     still possible. This should only be used if another transport security
  ##     mechanism like WireGuard is in place.
  ##     mechanism like WireGuard is in place 
  #Eg. tls: 'strict'
  tls: 
  #Provide the at least one node to connect for bootstrap. This should be reachable from this node
  #Eg. othernodes: 'http://node1.quo.demo.aws.blockchaincloudpoc.com:15013/'
  othernodes: 

proxy:
  #This will be the proxy/ingress provider. Can have values "ambassador" or "haproxy"
  # TODO "haproxy" has not been tested
  #Eg. provider: "ambassador"
  provider: "ambassador"
  #This field contains the external URL suffix of the organization
  #Eg. external_url_suffix: org1.blockchaincloudpoc.com
  external_url_suffix:
  # Following are the ports that are exposed externally via the proxy
  rpcport: 15010
  quorumport: 15011
  portConst: 15013
  portRaft: 15012

storage:
  #Provide the kubernetes storageclass for node
  #Eg. storageclassname: awsstorageclass
  storageclassname: 
  #Provide the memory for node
  #Eg. storagesize: 1Gi
  storagesize: 
