# This task checks if the crypto material is already stored in the vault or not
- name: Check if nodekey already present in the vault
  shell: |
    vault read secret/{{ component_ns }}/crypto/{{ component_name }}/quorum/nodekey
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  register: vault_nodekey_result
  ignore_errors: yes

# This task creates the build directory if it does not exist
- name: Create build directory if it does not exist
  file:
    path: build
    state: directory
    mode: '0755'

# This task generates the crypto material for the node having raft consensus
- name: Generate crypto for raft consensus
  shell: |
    mkdir build/{{ component_name }}
    bootnode -genkey build/{{ component_name }}/nodekey
    bootnode --nodekey=build/{{ component_name }}/nodekey --writeaddress > build/{{ component_name }}/enode
    echo {{ peer.geth_passphrase }} >> build/{{ component_name }}/password
    geth account new --datadir build/{{ component_name }} --password build/{{ component_name }}/password
    cp build/{{ component_name }}/keystore/* build/{{ component_name }}/keystore.json
  when: vault_nodekey_result.failed == True

# This tasks copy the crypto material to the vault
- name: Copy the crypto material to Vault
  shell: |
    vault kv put secret/{{ component_ns }}/crypto/{{ component_name }}/quorum nodekey="$(cat build/{{ component_name}}/nodekey)" keystore="$(cat build/{{ component_name }}/keystore.json)" db_user="demouser" db_password="password" gethpassword="$(cat build/{{ component_name }}/password)"
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  when: vault_nodekey_result.failed == True


